# in order to DRY,we can use common config 
# common config
 common: &common
   adapter: mysql2
   encoding: utf8
   pool: 10
   username: root
   password:
   host: localhost
   port: 3306
 
# development config
 development:
   database: chater
   <<: *common
 
# test config
 test:
   database: chater_test
   <<: *common
   
#production config    
 production:
   <<: *common
   database: chater
